# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sanlee <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/04 17:43:24 by sanlee            #+#    #+#              #
#    Updated: 2019/11/05 11:26:15 by sanlee           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op
SRCS = srcs/do_op.c srcs/ft_atoi.c srcs/ft_opertor.c srcs/ft_usage.c

all : 
	gcc $(SRCS) -o $(NAME)

clean : 
	/bin/rm -f $(NAME)

re : clean all
